---
- name: execute a mongodb query on hosts
  hosts: "{{ HOSTS }}"
  remote_user: root

  tasks:
  - name: run a backup script to take MongoDB backup
    command: bash /root/scripts/mongodb_backup.sh

  - name: get the mongo db query to execute
    get_url:
      url: https://ssstg.mkcl.org/files/"{{ QUERY_FILE_NAME }}"
      dest: /tmp/"{{ QUERY_FILE_NAME }}"
      mode: 0644

  - name: execute the query
    shell: mongo -u "{{ DB_USERNAME }}" -p'"{{ DB_PASSWORD }}"' --authenticationDatabase "{{ DB_NAME }}" </tmp/"{{ QUERY_FILE_NAME }}"

      
            