---
- hosts: "{{ HOSTS }}"
  become: yes

  tasks:
    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        
    - name: Disable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present

    - name: Limit max auth try
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries'
        line: "MaxAuthTries 3"
        state: present

    - name: Limit login grace time
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^LoginGraceTime'
        line: "LoginGraceTime 20m"
        state: present

    - name: Deny empty passwords
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitEmptyPasswords'
        line: "PermitEmptyPasswords no"
        state: present

    - name: Allow only sudo users to take SSH access
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          AllowGroups sudo
           
    - name: restart the ssh service
      service:
        name: ssh
        state: restarted